/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xdev_mxdev_MXRecvRequest */

#ifndef _Included_xdev_mxdev_MXRecvRequest
#define _Included_xdev_mxdev_MXRecvRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xdev_mxdev_MXRecvRequest
 * Method:    nativeIwait
 * Signature: (Lmpjdev/Status;)V
 */
JNIEXPORT void JNICALL Java_xdev_mxdev_MXRecvRequest_nativeIwait
  (JNIEnv *, jobject, jobject);

/*
 * Class:     xdev_mxdev_MXRecvRequest
 * Method:    nativeItest
 * Signature: (Lmpjdev/Status;)I
 */
JNIEXPORT jint JNICALL Java_xdev_mxdev_MXRecvRequest_nativeItest
  (JNIEnv *, jobject, jobject);

/*
 * Class:     xdev_mxdev_MXRecvRequest
 * Method:    nativeRequestInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xdev_mxdev_MXRecvRequest_nativeRequestInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
