package CorbaBasicModule;


/**
* CorbaBasicModule/CorbaBasicHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaBasicModule.idl
* Friday, 5 March 2021 13:40:50 o'clock IST
*/

abstract public class CorbaBasicHelper
{
  private static String  _id = "IDL:CorbaBasicModule/CorbaBasic:1.0";

  public static void insert (org.omg.CORBA.Any a, CorbaBasicModule.CorbaBasic that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CorbaBasicModule.CorbaBasic extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaBasicModule.CorbaBasicHelper.id (), "CorbaBasic");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CorbaBasicModule.CorbaBasic read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaBasicStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaBasicModule.CorbaBasic value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CorbaBasicModule.CorbaBasic narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaBasicModule.CorbaBasic)
      return (CorbaBasicModule.CorbaBasic)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaBasicModule._CorbaBasicStub stub = new CorbaBasicModule._CorbaBasicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CorbaBasicModule.CorbaBasic unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CorbaBasicModule.CorbaBasic)
      return (CorbaBasicModule.CorbaBasic)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CorbaBasicModule._CorbaBasicStub stub = new CorbaBasicModule._CorbaBasicStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
