package CorbaBasicModule;


/**
* CorbaBasicModule/CorbaBasic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaBasicModule.idl
* Tuesday, 16 March, 2021 4:02:56 PM IST
*/

public interface CorbaBasic extends CorbaBasicOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaBasic
