package CorbaBasicModule;

/**
* CorbaBasicModule/CorbaBasicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaBasicModule.idl
* Friday, 5 March 2021 13:40:50 o'clock IST
*/

public final class CorbaBasicHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaBasicModule.CorbaBasic value = null;

  public CorbaBasicHolder ()
  {
  }

  public CorbaBasicHolder (CorbaBasicModule.CorbaBasic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CorbaBasicModule.CorbaBasicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CorbaBasicModule.CorbaBasicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CorbaBasicModule.CorbaBasicHelper.type ();
  }

}
