package CorbaBasicModule;


/**
* CorbaBasicModule/CorbaBasicOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaBasicModule.idl
* Friday, 5 March 2021 13:40:50 o'clock IST
*/

public interface CorbaBasicOperations 
{
  String process_string (String str);
} // interface CorbaBasicOperations
