package CorbaBasicModule;


/**
* CorbaBasicModule/CorbaBasic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaBasicModule.idl
* Friday, 5 March 2021 13:40:50 o'clock IST
*/

public interface CorbaBasic extends CorbaBasicOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaBasic
