/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_Intercomm */

#ifndef _Included_mpjdev_natmpjdev_Intercomm
#define _Included_mpjdev_natmpjdev_Intercomm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpjdev_natmpjdev_Intercomm
 * Method:    nativeMerge
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_mpjdev_natmpjdev_Intercomm_nativeMerge
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
