/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_Intracomm */

#ifndef _Included_mpjdev_natmpjdev_Intracomm
#define _Included_mpjdev_natmpjdev_Intracomm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_init
  (JNIEnv *, jclass);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeCompare
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeCompare
  (JNIEnv *, jclass, jlong, jlong);


/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeBarrier
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeBarrier
  (JNIEnv *, jobject, jlong);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeBcast
 * Signature: (JLjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeBcast
  (JNIEnv *, jobject, jlong, jobject, jint, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeGather
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIZ)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeGather
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jint, jboolean);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeGatherv
 * Signature: (JLmpjbuf/Buffer;ILmpjbuf/Buffer;[I[II)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeGatherv
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jintArray, jintArray, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeScatter
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeScatter
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeScatterv
 * Signature: (JLjava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeScatterv
  (JNIEnv *, jobject, jlong, jobject, jintArray, jintArray, jobject, jint, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeAllgather
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeAllgather
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeAllgatherv
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;[I[I)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeAllgatherv
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jintArray, jintArray);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeAlltoall
 * Signature: (JLjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeAlltoall
  (JNIEnv *, jobject, jlong, jobject, jint, jobject, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeAlltoallv
 * Signature: (JLjava/nio/ByteBuffer;[I[ILjava/nio/ByteBuffer;[I[I)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeAlltoallv
  (JNIEnv *, jobject, jlong, jobject, jintArray, jintArray, jobject, jintArray, jintArray);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeReduce
 * Signature: (JLjava/lang/Object;Ljava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeReduce
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeAllreduce
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILmpi/Op;)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeAllreduce
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jobject);

/*
 * Class:     mpjdev_natmpjdev_Intracomm
 * Method:    nativeReduce_scatter
 * Signature: (JLjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[ILmpi/Op;)V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_Intracomm_nativeReduce_1scatter
  (JNIEnv *, jobject, jlong, jobject, jobject, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
