/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_NativeRecvRequest */

#ifndef _Included_mpjdev_natmpjdev_NativeRecvRequest
#define _Included_mpjdev_natmpjdev_NativeRecvRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpjdev_natmpjdev_NativeRecvRequest
 * Method:    initNativeRecvRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_NativeRecvRequest_initNativeRecvRequest
  (JNIEnv *, jclass);

/*
 * Class:     mpjdev_natmpjdev_NativeRecvRequest
 * Method:    Wait
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeRecvRequest_Wait
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mpjdev_natmpjdev_NativeRecvRequest
 * Method:    Test
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeRecvRequest_Test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
