/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpjdev_natmpjdev_NativeSendRequest */

#ifndef _Included_mpjdev_natmpjdev_NativeSendRequest
#define _Included_mpjdev_natmpjdev_NativeSendRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpjdev_natmpjdev_NativeSendRequest
 * Method:    initNativeSendRequest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_mpjdev_natmpjdev_NativeSendRequest_initNativeSendRequest
  (JNIEnv *, jclass);

/*
 * Class:     mpjdev_natmpjdev_NativeSendRequest
 * Method:    Wait
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeSendRequest_Wait
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mpjdev_natmpjdev_NativeSendRequest
 * Method:    Test
 * Signature: (Lmpjdev/Status;)Lmpjdev/Status;
 */
JNIEXPORT jobject JNICALL Java_mpjdev_natmpjdev_NativeSendRequest_Test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
