module TTTModule
{
    interface TTT
    {
        long howFull(in string boardStr);
        boolean isValidMove(in long move, in string boardStr);
        long serverMove(in string boardStr);
        long determineWinner(in string boardStr);
    };
};