package TTTModule;


/**
* TTTModule/TTT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Tuesday, 9 March 2021 22:22:34 o'clock IST
*/

public interface TTT extends TTTOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TTT
