package TTTModule;


/**
* TTTModule/TTT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Friday, 21 May, 2021 2:49:01 PM IST
*/

public interface TTT extends TTTOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TTT
