package TTTModule;


/**
* TTTModule/TTT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Wednesday, 10 March 2021 10:57:46 o'clock IST
*/

public interface TTT extends TTTOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TTT
