package TTTModule;


/**
* TTTModule/TTTOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Friday, 21 May, 2021 2:49:01 PM IST
*/

public interface TTTOperations 
{
  int howFull (String boardStr);
  boolean isValidMove (int move, String boardStr);
  int serverMove (String boardStr);
  int determineWinner (String boardStr);
} // interface TTTOperations
