package TTTModule;


/**
* TTTModule/TTTOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Wednesday, 10 March 2021 10:57:46 o'clock IST
*/

public interface TTTOperations 
{
  int howFull (String boardStr);
  boolean isValidMove (int move, String boardStr);
  int serverMove (String boardStr);
  int determineWinner (String boardStr);
} // interface TTTOperations
