package TTTModule;


/**
* TTTModule/TTTOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Friday, 5 March 2021 14:18:47 o'clock IST
*/

public interface TTTOperations 
{
  String process_string (String str);
} // interface TTTOperations
