package TTTModule;


/**
* TTTModule/TTTPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TTTModule.idl
* Wednesday, 10 March 2021 10:57:46 o'clock IST
*/

public abstract class TTTPOA extends org.omg.PortableServer.Servant
 implements TTTModule.TTTOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("howFull", new java.lang.Integer (0));
    _methods.put ("isValidMove", new java.lang.Integer (1));
    _methods.put ("serverMove", new java.lang.Integer (2));
    _methods.put ("determineWinner", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TTTModule/TTT/howFull
       {
         String boardStr = in.read_string ();
         int $result = (int)0;
         $result = this.howFull (boardStr);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // TTTModule/TTT/isValidMove
       {
         int move = in.read_long ();
         String boardStr = in.read_string ();
         boolean $result = false;
         $result = this.isValidMove (move, boardStr);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // TTTModule/TTT/serverMove
       {
         String boardStr = in.read_string ();
         int $result = (int)0;
         $result = this.serverMove (boardStr);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // TTTModule/TTT/determineWinner
       {
         String boardStr = in.read_string ();
         int $result = (int)0;
         $result = this.determineWinner (boardStr);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TTTModule/TTT:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TTT _this() 
  {
    return TTTHelper.narrow(
    super._this_object());
  }

  public TTT _this(org.omg.CORBA.ORB orb) 
  {
    return TTTHelper.narrow(
    super._this_object(orb));
  }


} // class TTTPOA
